# Generated by Django 3.2 on 2021-04-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0004_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='note_text',
        ),
    ]
