# Generated by Django 3.2 on 2021-04-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0021_alter_question_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
    ]
