# Generated by Django 3.2 on 2021-04-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20210429_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionChoiceVotes',
            new_name='QuestionChoiceVote',
        ),
    ]
