# Generated by Django 3.2 on 2021-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
