# Generated by Django 3.2 on 2021-04-23 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0008_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll_app.language'),
            preserve_default=True,
        ),
    ]
