# Generated by Django 3.2 on 2021-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0032_auto_20210429_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(to='poll_app.Choice'),
        ),
    ]
