# Generated by Django 3.2 on 2021-04-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0033_auto_20210429_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.CreateModel(
            name='QuestionChoiceVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('choice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll_app.choice')),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll_app.question')),
            ],
        ),
    ]
