# Generated by Django 3.2 on 2021-05-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0035_rename_questionchoicevotes_questionchoicevote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='questiontype',
            name='question_type',
            field=models.ForeignKey(default=None, null=True , on_delete=django.db.models.deletion.CASCADE, to='poll_app.question'),
            preserve_default=True,
        ),
    ]
