# Generated by Django 3.2 on 2021-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
